export const quotes = [
  'Cuộc sống là một chuyến đi, không phải là đích đến. - Ralph Waldo Emerson',
  'Hạnh phúc không phải là thứ bạn trì hoãn đến tương lai; nó là thứ bạn thiết kế cho hiện tại. - Jim Rohn',
  'Tôi không thất bại, tôi chỉ tìm ra 10.000 cách không hoạt động. - Thomas Edison',
  'Cuộc sống giống như Wi-Fi, bạn không thấy nó nhưng vẫn cần nó! - Anonymous',
  'Đừng chờ đợi cơ hội, hãy tạo ra nó. - George Bernard Shaw',
  'Thành công là đi từ thất bại này đến thất bại khác mà không mất đi nhiệt huyết. - Winston Churchill',
  'Bạn không cần phải giỏi để bắt đầu, nhưng bạn phải bắt đầu để trở nên giỏi. - Zig Ziglar',
  'Mọi thứ bạn muốn đều nằm ở phía bên kia của nỗi sợ hãi. - George Addair',
  'Thời gian là vàng, nhưng vàng chẳng mua được thời gian. - Tục ngữ',
  'Cuộc sống là 10% những gì xảy ra với bạn và 90% cách bạn phản ứng với nó. - Charles R. Swindoll',
  'Người bi quan thấy khó khăn trong mọi cơ hội; người lạc quan thấy cơ hội trong mọi khó khăn. - Winston Churchill',
  'Hãy là chính mình; mọi người khác đã có người đảm nhận rồi. - Oscar Wilde',
  'Đừng mơ về thành công, hãy làm việc để đạt được nó. - Estée Lauder',
  'Cuộc sống giống như một cuốn sách, hãy viết nên câu chuyện đáng để đọc. - Anonymous',
  'Không có gì là không thể, chính từ đó đã nói "Tôi có thể" (I`m possible). - Audrey Hepburn',
  'Đừng tìm kiếm ánh sáng ở cuối đường hầm, hãy tự thắp nó lên. - Anonymous',
  'Cuộc sống là một bài kiểm tra, và bạn là người chấm điểm. - Unknown',
  'Hãy sống như thể bạn sẽ chết ngày mai, học như thể bạn sẽ sống mãi mãi. - Mahatma Gandhi',
  'Thất bại là gia vị làm nên hương vị của thành công. - Truman Capote',
  'Cuộc sống không phải là tìm kiếm bản thân, mà là tạo ra chính mình. - George Bernard Shaw',
  'Từng bước nhỏ hôm nay sẽ dẫn bạn đến những nơi tuyệt vời ngày mai. - Anonymous',
  'Hãy làm điều bạn yêu thích, và bạn sẽ không phải làm việc một ngày nào trong đời. - Confucius',
  'Thời gian bạn thích lãng phí không phải là thời gian lãng phí. - John Lennon',
  'Cuộc sống giống như cưỡi xe đạp, để giữ thăng bằng bạn phải tiếp tục di chuyển. - Albert Einstein',
  'Hãy mơ lớn, làm việc chăm chỉ, và đừng bao giờ từ bỏ. - Anonymous',
  'Thành công không phải là chìa khóa của hạnh phúc; hạnh phúc là chìa khóa của thành công. - Albert Schweitzer',
  'Cuộc sống là một trò chơi, hãy chơi hết mình. - Anonymous',
  'Hãy thay đổi cách bạn nhìn nhận, và thế giới xung quanh bạn sẽ thay đổi. - Wayne Dyer',
  'Đừng đếm ngày, hãy làm cho mỗi ngày đáng đếm. - Muhammad Ali',
  'Cuộc sống là một cơ hội, hãy nắm lấy nó. - Mother Teresa',
  'Cơ hội giống như bình minh, nếu bạn đợi quá lâu, bạn sẽ bỏ lỡ nó. - William Arthur Ward',
  'Cuộc sống là nghệ thuật vẽ mà không có cục tẩy. - John W. Gardner',
  'Hãy mỉm cười, vì bạn không bao giờ biết ai sẽ yêu nụ cười ấy. - Anonymous',
  'Đừng sợ thất bại, hãy sợ việc không cố gắng. - Anonymous',
  'Cuộc sống là một cuộc phiêu lưu, hãy dũng cảm bước đi. - Anonymous',
  'Hạnh phúc là khi bạn nghĩ, nói và làm đều hòa hợp. - Mahatma Gandhi',
  'Cuộc sống giống như một chiếc gương, bạn cười với nó, nó sẽ cười lại. - Anonymous',
  'Đừng sống để làm hài lòng người khác, hãy sống cho chính mình. - Anonymous',
  'Thành công không đến từ những gì bạn có, mà từ những gì bạn làm với nó. - Anonymous',
  'Cuộc sống là một món quà, hãy mở nó ra mỗi ngày. - Anonymous',
  'Hãy đi chậm nếu cần, nhưng đừng dừng lại. - Anonymous',
  'Cuộc sống là những gì xảy ra khi bạn đang bận lập kế hoạch khác. - John Lennon',
  'Từng khoảnh khắc là một khởi đầu mới. - T.S. Eliot',
  'Hãy sống thật với bản thân, đó là cách duy nhất để hạnh phúc. - Anonymous',
  'Cuộc sống giống như một bài hát, hãy tìm giai điệu của riêng bạn. - Anonymous',
  'Đừng sợ khác biệt, hãy sợ giống hệt mọi người. - Anonymous',
  'Cuộc sống là một câu hỏi, và cách bạn sống là câu trả lời. - Anonymous',
  'Hãy yêu thương bản thân, vì bạn là người duy nhất sống cả đời với bạn. - Anonymous',
  'Cuộc sống giống như một cơn gió, bạn không thể nắm giữ nó, chỉ có thể cảm nhận. - Anonymous',
  'Đừng để hôm qua chiếm quá nhiều của hôm nay. - Will Rogers',
  'Cuộc sống là một bức tranh, hãy tô màu theo cách của bạn. - Anonymous',
  'Hãy làm điều khiến trái tim bạn rung động. - Anonymous',
  'Cuộc sống giống như một chiếc cầu vồng, cần cả mưa và nắng để thấy được màu sắc. - Anonymous',
  'Đừng chờ đợi thời điểm hoàn hảo, hãy biến khoảnh khắc này thành hoàn hảo. - Anonymous',
  'Cuộc sống là một cuộc chạy marathon, không phải là một cuộc đua nước rút. - Anonymous',
  'Hãy tin vào chính mình, ngay cả khi không ai khác làm điều đó. - Anonymous',
  'Cuộc sống giống như một cuốn tiểu thuyết, mỗi ngày là một trang mới. - Anonymous',
  'Đừng để nỗi sợ thất bại ngăn bạn thử sức. - Anonymous',
  'Cuộc sống là một vòng tròn, những gì bạn cho đi sẽ quay trở lại. - Anonymous',
  'Hãy sống chậm lại và tận hưởng từng khoảnh khắc. - Anonymous',
  'Cuộc sống giống như một trò đùa, hãy cười thật to. - Anonymous',
  'Đừng tìm kiếm ý nghĩa của cuộc sống, hãy tạo ra nó. - Anonymous',
  'Cuộc sống là một hành trình học hỏi không ngừng. - Anonymous',
  'Hãy sống như thể hôm nay là ngày cuối cùng, yêu như thể bạn chưa từng tổn thương. - Anonymous',
  'Cuộc sống giống như một chiếc đồng hồ, mỗi giây đều đáng giá. - Anonymous',
  'Đừng sống trong quá khứ, hãy xây dựng tương lai. - Anonymous',
  'Cuộc sống là một cuộc chiến, hãy chọn những trận đánh đáng giá. - Anonymous',
  'Hãy là ánh sáng trong bóng tối của chính mình. - Anonymous',
  'Cuộc sống giống như một con đường, hãy chọn lối đi của riêng bạn. - Anonymous',
  'Đừng để giấc mơ chỉ là giấc mơ, hãy biến chúng thành hiện thực. - Anonymous',
  'Cuộc sống là một bài học, và bạn là học sinh mãi mãi. - Anonymous',
  'Hãy sống với đam mê, vì đó là nhiên liệu của linh hồn. - Anonymous',
  'Cuộc sống giống như một cơn mưa, hãy học cách nhảy múa dưới nó. - Anonymous',
  'Đừng để ai đánh cắp nụ cười của bạn. - Anonymous',
  'Cuộc sống là một món quà, đừng quên cảm ơn mỗi ngày. - Anonymous',
  'Hãy sống thật lớn, ngay cả trong những ngày nhỏ bé. - Anonymous',
  'Cuộc sống giống như một tấm gương, bạn thấy những gì bạn phản chiếu. - Anonymous',
  'Đừng sợ bắt đầu lại, đó là cơ hội để làm tốt hơn. - Anonymous',
  'Cuộc sống là một câu chuyện, hãy làm cho nó đáng nhớ. - Anonymous',
  'Hãy sống với lòng biết ơn, và mọi thứ sẽ thay đổi. - Anonymous',
  'Cuộc sống giống như một ngọn lửa, hãy giữ nó cháy sáng. - Anonymous',
  'Đừng chờ đợi phép màu, hãy tự tạo ra chúng. - Anonymous',
  'Cuộc sống là một bí ẩn, hãy tận hưởng việc khám phá. - Anonymous',
  'Hãy sống như thể bạn không có gì để mất. - Anonymous',
  'Cuộc sống giống như một dòng sông, hãy để nó chảy theo cách của bạn. - Anonymous',
  'Đừng để nỗi buồn hôm nay che mờ niềm vui ngày mai. - Anonymous',
  'Cuộc sống là một cuộc phiêu lưu, hãy tận hưởng từng bước đi. - Anonymous',
  'Hãy sống với trái tim rộng mở và tâm hồn tự do. - Anonymous',
  'Cuộc sống giống như một bài thơ, hãy viết nên những vần điệu đẹp. - Anonymous',
  'Đừng sợ thất bại, đó chỉ là một bài học trá hình. - Anonymous',
  'Cuộc sống là một kho báu, hãy tìm kiếm những viên ngọc ẩn giấu. - Anonymous',
  'Hãy sống như thể mỗi ngày là một kỳ nghỉ. - Anonymous',
  'Cuộc sống giống như một cánh cửa, hãy mở nó ra và bước qua. - Anonymous',
  'Đừng để ai định nghĩa cuộc sống của bạn, hãy tự viết câu chuyện của mình. - Anonymous',
  'Cuộc sống là một bức tranh ghép, mỗi mảnh đều quan trọng. - Anonymous',
  'Hãy sống với lòng can đảm, ngay cả khi bạn sợ hãi. - Anonymous',
  'Cuộc sống giống như một ngôi sao, hãy làm cho nó tỏa sáng. - Anonymous',
  'Đừng sống chỉ để tồn tại, hãy sống để tạo ra sự khác biệt. - Anonymous',
  'Cuộc sống là một giấc mơ, hãy biến nó thành hiện thực. - Anonymous',
  'Bạch tuộc có 3 trái tim và có thể đổi màu để ngụy trang.',
  'Một ngày trên sao Kim dài hơn một năm trên sao Kim.',
  'Mèo ngủ trung bình 15 tiếng mỗi ngày, thật đáng ghen tị!',
  'Cá voi xanh là động vật lớn nhất từng sống trên Trái Đất, nặng tới 200 tấn.',
  'Mật ong không bao giờ hỏng - người ta tìm thấy mật ong 3.000 năm tuổi vẫn ăn được!',
  'Loài nhện có thể sống sót trong không gian vũ trụ.',
  'Mặt trời chiếm 99,86% khối lượng của Hệ Mặt Trời.',
  'Cá mập có khứu giác nhạy gấp 10.000 lần con người.',
  'Một con kiến có thể nâng vật nặng gấp 50 lần trọng lượng cơ thể nó.',
  'Trái Đất có hơn 8 triệu loài sinh vật, nhưng chúng ta mới chỉ khám phá khoảng 15%.',
  'Tê giác trắng là loài động vật lớn thứ hai trên cạn, sau voi.',
  'Sét đánh vào Trái Đất khoảng 8 triệu lần mỗi ngày.',
  'Cá heo ngủ với một mắt mở để cảnh giác kẻ thù.',
  'Mỗi năm, con người uống khoảng 2,5 nghìn tỷ cốc cà phê trên toàn cầu.',
  'Loài chim ruồi có thể bay ngược - loài chim duy nhất làm được điều này.',
  'Loài sứa không có não nhưng vẫn sống sót hàng triệu năm.',
  'Mặt trăng đang dần rời xa Trái Đất khoảng 3,8 cm mỗi năm.',
  'Một con bò trung bình thải ra 200 lít khí metan mỗi ngày.',
  'Loài rắn có thể sống sót 6 tháng mà không cần ăn.',
  'Trái tim của tôm nằm ở đầu nó.',
  'Cá ngựa là loài duy nhất mà con đực mang thai.',
  'Một con dơi có thể ăn tới 1.000 con côn trùng trong một giờ.',
  'Loài kangaroo không thể nhảy lùi lại được.',
  'Mực khổng lồ có đôi mắt to bằng quả bóng rổ.',
  'Trái Đất có khoảng 40.000 trận động đất mỗi năm.',
  'Loài chim cánh cụt có thể bơi với tốc độ 36 km/h.',
  'Một con ốc sên có thể ngủ liên tục 3 năm.',
  'Loài báo săn là động vật chạy nhanh nhất trên cạn, đạt 120 km/h.',
  'Cây cao nhất thế giới là một cây hồng sam cao 115 mét ở California.',
  'Loài bướm có thể nhìn thấy màu sắc mà con người không thấy được.',
  'Nước chiếm 71% bề mặt Trái Đất nhưng chỉ 0,5% là nước uống được.',
  'Loài hà mã có thể chạy nhanh hơn con người trên cạn.',
  'Một con ong mật phải bay 88.000 km để tạo ra 0,5 kg mật.',
  'Loài voi không bao giờ quên - trí nhớ của chúng cực kỳ tốt.',
  'Mỗi phút, có khoảng 120 triệu email được gửi trên toàn cầu.',
  'Loài gấu trúc không thực sự ngủ đông như gấu khác.',
  'Cá voi sát thủ thực chất là một loài cá heo.',
  'Một con hàu có thể lọc 190 lít nước mỗi ngày.',
  'Loài lạc đà có thể uống 113 lít nước trong 13 phút.',
  'Trái Đất quay chậm dần qua hàng triệu năm.',
  'Loài rùa có thể sống hơn 150 năm.',
  'Một con bạch tuộc có thể tự cắt bỏ xúc tu để thoát thân.',
  'Loài cá mập không có xương, cơ thể chúng làm từ sụn.',
  'Mỗi ngày, con người hít thở khoảng 11.000 lít không khí.',
  'Loài cá sấu có thể nhịn thở dưới nước tới 1 giờ.',
  'Một con mèo có thể nhảy cao gấp 5 lần chiều cao cơ thể nó.',
  'Loài sư tử ngủ tới 20 tiếng mỗi ngày.',
  'Trái Đất có 5 đại dương nhưng chỉ 1 đại dương toàn cầu.',
  'Loài cáo có thể nghe thấy tiếng động từ cách xa 40 mét.',
  'Một con chim ưng có thể nhìn thấy con mồi từ khoảng cách 3 km.',
  'Loài cá hề sống cộng sinh với hải quỳ để tránh kẻ thù.',
  'Một con chuột có thể sống sót khi rơi từ độ cao 15 mét.',
  'Loài khỉ có thể nhận ra mình trong gương, giống con người.',
  'Mỗi năm, có khoảng 1.000 cơn lốc xoáy xảy ra trên toàn cầu.',
  'Loài ngựa vằn có sọc đen trắng để đánh lừa kẻ thù.',
  'Một con cá voi có thể phát ra âm thanh lớn tới 188 decibel.',
  'Loài chuồn chuồn có thể bay với tốc độ 54 km/h.',
  'Trái Đất mất 23 giờ 56 phút để quay một vòng, không phải 24 giờ.',
  'Loài chó có khứu giác nhạy gấp 10.000 lần con người.',
  'Một con hươu cao cổ có cổ dài tới 1,8 mét.',
  'Loài bò sát có thể thay đổi giới tính tùy theo nhiệt độ.',
  'Mỗi ngày, có khoảng 100.000 chuyến bay cất cánh trên toàn cầu.',
  'Loài cá mập trắng có thể ngửi thấy máu trong nước từ cách xa 5 km.',
  'Một con gấu bắc cực có thể bơi liên tục 100 km.',
  'Loài chim ó có thể phát hiện nhiệt từ cơ thể con mồi.',
  'Trái Đất có hơn 1,3 triệu loài côn trùng đã được phát hiện.',
  'Loài dê có đồng tử mắt hình chữ nhật.',
  'Một con sói có thể ăn tới 9 kg thịt trong một lần.',
  'Loài cá voi lưng gù hát những bài hát dài tới 20 phút.',
  'Mỗi ngày, có khoảng 2.000 ngôi sao mới sinh ra trong vũ trụ.',
  'Loài hươu đực mọc lại sừng mỗi năm.',
  'Một con nhện có thể dệt lưới trong vòng 1 giờ.',
  'Loài cá hồi có thể bơi ngược dòng thác để đẻ trứng.',
  'Trái Đất có khoảng 7.000 ngôn ngữ khác nhau.',
  'Loài chim bồ câu có thể nhớ tới 700 hình ảnh khác nhau.',
  'Một con sư tử cái săn mồi giỏi hơn sư tử đực.',
  'Loài kỳ nhông có thể mọc lại đuôi nếu bị mất.',
  'Mỗi giây, có khoảng 100 tia sét đánh xuống Trái Đất.',
  'Loài chuột chũi có thể đào 18 mét đường hầm trong 1 ngày.',
  'Một con cá voi có thể nín thở tới 2 giờ.',
  'Loài chim sẻ có thể bay với tốc độ 38 km/h.',
  'Trái Đất có hơn 10.000 loài chim khác nhau.',
  'Loài ngựa có thể ngủ đứng nhờ cơ chế khóa khớp.',
  'Một con cá mập có thể mọc hơn 20.000 chiếc răng trong đời.',
  'Loài tắc kè có thể thay đổi màu sắc để giao tiếp.',
  'Mỗi năm, có khoảng 500 phim được sản xuất tại Hollywood.',
  'Loài cá chình điện có thể phóng điện tới 600 volt.',
  'Một con thỏ có thể sinh tới 12 con trong một lứa.',
  'Loài chim hồng hạc đứng một chân để giữ nhiệt.',
  'Trái Đất có hơn 1 triệu loài động vật có xương sống.',
  'Loài cáo Bắc Cực có bộ lông đổi màu theo mùa.',
  'Một con ếch có thể nhảy xa gấp 20 lần chiều dài cơ thể nó.',
  'Loài gấu túi ngủ tới 22 tiếng mỗi ngày.',
  'Mỗi ngày, có khoảng 4 tỷ tin nhắn được gửi qua WhatsApp.',
  'Loài cá mập voi là loài cá lớn nhất thế giới, dài tới 12 mét.',
  'Một con hà mã có thể mở miệng rộng tới 1,2 mét.',
  'Loài ong thợ chỉ sống khoảng 6 tuần vào mùa hè.',
  'Trái Đất có hơn 3.000 loài rắn khác nhau.',
  'Loài cú có thể xoay đầu 270 độ mà không đau.',
  'Tôi không lười, tôi chỉ đang ở chế độ tiết kiệm năng lượng.',
  'Cuộc sống giống như cà phê: đắng, nhưng phải uống.',
  'Tôi không béo, tôi chỉ dễ nhìn thấy hơn thôi!',
  'Tiền không mua được hạnh phúc, nhưng nó mua được trà sữa, cũng gần giống vậy.',
  'Tôi không ngủ quên, tôi chỉ đang tập thiền với mắt nhắm.',
  'Nếu kế hoạch A thất bại, đừng lo, bảng chữ cái còn 25 chữ nữa.',
  'Tôi không cãi nhau, tôi chỉ giải thích tại sao tôi đúng.',
  'Cuộc sống là một trò đùa, nhưng tôi không hiểu punchline ở đâu.',
  'Tôi không già, tôi chỉ đang nâng cấp phần mềm đời mình.',
  'Nếu thời gian là tiền bạc, thì tôi là tỷ phú thất nghiệp.',
  'Tôi không phải người hay trì hoãn, tôi chỉ thích làm việc vào phút cuối để tăng adrenaline.',
  'Cuộc sống giống như Wi-Fi, lúc mạnh lúc yếu, chẳng ai hiểu nổi.',
  'Tôi không thất bại, tôi chỉ đang tìm cách sáng tạo để sai.',
  'Mỗi ngày tôi đều tập thể dục: nhấc điện thoại lên và đặt xuống.',
  'Tôi không lộn xộn, tôi chỉ đang tổ chức theo phong cách nghệ thuật.',
  'Nếu cuộc sống là một bộ phim, tôi chắc chắn là nhân vật phụ hài hước.',
  'Tôi không nghiện cà phê, chúng ta chỉ là bạn thân không thể tách rời.',
  'Cuộc sống giống như một cái pizza, ngay cả khi tệ thì vẫn ngon.',
  'Tôi không quên, tôi chỉ chọn lọc những thứ đáng nhớ.',
  'Nếu tôi có siêu năng lực, đó là khả năng ngủ mọi lúc mọi nơi.',
  'Tôi không chậm chạp, tôi chỉ sống ở chế độ slow-motion.',
  'Cuộc sống là một bữa tiệc, nhưng tôi đến muộn và hết đồ ăn.',
  'Tôi không phải người hướng nội, tôi chỉ thích nói chuyện với chính mình hơn.',
  'Nếu tôi là siêu anh hùng, sức mạnh của tôi là ăn hết đồ ăn vặt trong 5 phút.',
  'Tôi không lười biếng, tôi chỉ đang bảo tồn năng lượng cho tương lai.',
  'Cuộc sống giống như một bài kiểm tra, tôi không chuẩn bị nhưng vẫn cố làm.',
  'Tôi không thất tình, tôi chỉ đang tạm nghỉ để bảo trì trái tim.',
  'Nếu tôi có thể quay ngược thời gian, tôi sẽ ngủ thêm 5 phút nữa.',
  'Tôi không mất tập trung, tôi chỉ đang khám phá mọi khả năng cùng lúc.',
  'Cuộc sống giống như một cái remote, tôi chưa tìm ra nút pause.',
  'Tôi không vụng về, tôi chỉ đang thử nghiệm trọng lực quá thường xuyên.',
  'Nếu tôi là động vật, tôi sẽ là một con mèo: ngủ cả ngày và vẫn được yêu thương.',
  'Tôi không bỏ cuộc, tôi chỉ tạm hoãn chiến thắng.',
  'Cuộc sống giống như một cái meme, buồn cười nhưng đôi khi không hiểu nổi.',
  'Tôi không đói, tôi chỉ đang kiểm tra xem tủ lạnh có gì mới không.',
  'Nếu tôi giàu, tôi sẽ mua thêm thời gian để ngủ.',
  'Tôi không cô đơn, tôi chỉ thích bầu bạn với Wi-Fi hơn.',
  'Cuộc sống giống như một cái điện thoại, lúc nào cũng hết pin vào thời điểm quan trọng.',
  'Tôi không phải người bi quan, tôi chỉ là người lạc quan với kinh nghiệm.',
  'Nếu tôi là một cuốn sách, tôi sẽ là cuốn chưa ai đọc hết.',
  'Tôi không ngốc, tôi chỉ đang tiết kiệm IQ cho việc quan trọng.',
  'Cuộc sống giống như một cái ghế, lúc nào cũng thiếu chỗ ngồi thoải mái.',
  'Tôi không ngủ nhiều, tôi chỉ đang mơ mộng trong trạng thái tỉnh táo.',
  'Nếu tôi là siêu sao, tôi sẽ nổi tiếng vì khả năng ăn nhanh.',
  'Tôi không lười vận động, tôi chỉ thích vận động não hơn.',
  'Cuộc sống giống như một cái bánh, tôi luôn ăn phần ngon nhất trước.',
  'Tôi không thích drama, nhưng drama cứ thích tôi.',
  'Nếu tôi có thể nói chuyện với đồ ăn, tôi sẽ bảo nó đừng ngon quá.',
  'Tôi không sợ hãi, tôi chỉ đang kiểm tra độ bền của trái tim mình.',
  'Cuộc sống giống như một cái máy giặt, xoay vòng và đôi khi làm tôi chóng mặt.',
  'Tôi không quên sinh nhật, tôi chỉ nhớ nó vào ngày sai.',
  'Nếu tôi là chim, tôi sẽ bay thẳng đến quán cà phê gần nhất.',
  'Tôi không phải người hay lo lắng, tôi chỉ giỏi tưởng tượng kịch bản xấu.',
  'Cuộc sống giống như một bài hát, tôi luôn hát sai lời.',
  'Tôi không cần đồng hồ báo thức, cái bụng đói sẽ đánh thức tôi.',
  'Nếu tôi là cây, tôi sẽ là cây lười: không cần tưới vẫn sống.',
  'Tôi không thích chạy bộ, tôi chỉ chạy khi có đồ ăn miễn phí.',
  'Cuộc sống giống như một trò chơi, nhưng tôi chưa đọc hướng dẫn.',
  'Tôi không phải người sáng tạo, tôi chỉ giỏi sao chép ý tưởng.',
  'Nếu tôi là mèo, tôi sẽ có 9 mạng để ngủ thêm.',
  'Tôi không thích dọn dẹp, tôi chỉ đang tạo môi trường sống cho vi khuẩn.',
  'Cuộc sống giống như một cái tủ, đầy thứ tôi không cần nhưng vẫn giữ.',
  'Tôi không sợ deadline, tôi chỉ thích làm bạn với nó vào phút cuối.',
  'Nếu tôi là siêu nhân, tôi sẽ dùng siêu tốc độ để ăn hết buffet.',
  'Tôi không thích tranh luận, tôi chỉ thích thắng.',
  'Cuộc sống giống như một cái bàn, tôi luôn làm đổ mọi thứ lên đó.',
  'Tôi không phải người hay quên, tôi chỉ giỏi nhớ những thứ không quan trọng.',
  'Nếu tôi là chó, tôi sẽ sủa cả ngày chỉ để được chú ý.',
  'Tôi không thích thức khuya, nhưng đêm luôn gọi tên tôi.',
  'Cuộc sống giống như một cái quạt, thổi bay mọi kế hoạch của tôi.',
  'Tôi không phải người tham ăn, tôi chỉ muốn thử hết mọi món.',
  'Nếu tôi là mưa, tôi sẽ rơi vào ngày bạn quên ô.',
  'Tôi không thích chờ đợi, nhưng chờ đồ ăn thì được.',
  'Cuộc sống giống như một cái bút, tôi luôn hết mực vào lúc cần nhất.',
  'Tôi không phải người đa nhiệm, tôi chỉ giỏi làm nhiều thứ dở cùng lúc.',
  'Nếu tôi là hoa, tôi sẽ là hoa dại: mọc lung tung nhưng vẫn xinh.',
  'Tôi không thích học, tôi chỉ thích biết.',
  'Cuộc sống giống như một cái đồng hồ cát, tôi luôn chờ nó lật lại.',
  'Tôi không phải người hay cáu, tôi chỉ phản ứng nhanh với sự ngốc nghếch.',
  'Nếu tôi là siêu năng lực, tôi sẽ là khả năng biến cà phê thành năng lượng.',
  'Tôi không thích đi bộ, tôi chỉ đi khi có đích đến là đồ ăn.',
  'Cuộc sống giống như một cái hộp, tôi không biết bên trong là gì nhưng vẫn mở.',
  'Tôi không phải người hay mơ, tôi chỉ sống trong thế giới tưởng tượng.',
  'Nếu tôi là gió, tôi sẽ thổi bay mọi hóa đơn.',
  'Tôi không thích họp, tôi chỉ thích ngủ trong lúc họp.',
  'Cuộc sống giống như một cái đèn, tôi luôn quên bật nó lên.',
  'Tôi không phải người lười yêu, tôi chỉ đang chờ người hoàn hảo.',
  'Nếu tôi là cá, tôi sẽ bơi thẳng vào lưới đồ ăn.',
  'Tôi không thích sáng sớm, nhưng sáng sớm cứ thích tôi.',
  'Cuộc sống giống như một cái vòng tròn, tôi luôn quay lại chỗ cũ.',
  'Tôi không phải người hay cười, tôi chỉ thấy mọi thứ buồn cười.',
  'Nếu tôi là chim, tôi sẽ đậu trên vai bạn để xin đồ ăn.',
  'Tôi không thích làm việc nhóm, tôi chỉ thích làm đội trưởng.',
  'Cuộc sống giống như một cái bánh mì, tôi luôn ăn vụn trước.',
  'Tôi không phải người hay buồn, tôi chỉ giỏi giả vờ sâu sắc.',
  'Nếu tôi là mây, tôi sẽ che nắng cho bạn nhưng vẫn làm bạn ướt.',
  'Tôi không thích thất bại, nhưng thất bại cứ thích tôi.',
  'Tôi có một trò đùa về cái chết, nhưng nó không còn sống nữa.',
  'Cuộc sống giống như một bộ phim kinh dị, tôi chỉ đang chờ phần jump scare.',
  'Tôi không tự tử, tôi chỉ muốn kiểm tra xem dây thừng có chắc không.',
  'Hôm nay là một ngày tuyệt vời để không tồn tại.',
  'Tôi có một trái tim, nhưng nó đen như màn hình xanh chết chóc.',
  'Cuộc sống giống như cà phê, đắng và cuối cùng cũng giết chết bạn.',
  'Tôi không cô đơn, tôi chỉ thích nói chuyện với bóng tối hơn.',
  'Ước mơ của tôi là không có ước mơ nào cả.',
  'Tôi không buồn, tôi chỉ đang tập làm zombie trước khi chết thật.',
  'Cuộc sống giống như một trò chơi, nhưng tôi quên mã cheat để thoát ra.',
  'Tôi không thất bại, tôi chỉ thành công trong việc thất vọng.',
  'Mặt trời mọc mỗi ngày để nhắc tôi rằng tôi vẫn chưa thoát khỏi đây.',
  'Tôi không có vấn đề tâm lý, tôi chỉ là fan cuồng của bóng tối.',
  'Cuộc sống giống như một chiếc gương, nó phản chiếu những gì tôi ghét.',
  'Tôi không ghét mọi người, tôi chỉ thích họ hơn khi họ không tồn tại.',
  'Tôi có một danh sách việc cần làm: ngủ, chết, lặp lại.',
  'Cuộc sống giống như Wi-Fi, lúc có lúc không, chủ yếu là không.',
  'Tôi không phải người bi quan, tôi chỉ thấy ánh sáng ở cuối đường hầm là tàu hỏa.',
  'Tôi không khóc, mắt tôi chỉ đang thử nghiệm hệ thống tưới nước.',
  'Cuộc sống giống như một cuốn sách, tôi muốn đốt nó.',
  'Tôi không sợ chết, tôi chỉ không muốn gặp lại mấy người ở dưới đó.',
  'Tôi có một trò đùa về gia đình, nhưng họ đã bỏ tôi đi rồi.',
  'Cuộc sống giống như một cái bánh, tôi muốn ai đó đâm nó chết đi.',
  'Tôi không tuyệt vọng, tôi chỉ đang tìm lý do để không thức dậy.',
  'Tôi không cô độc, tôi có cái bóng của mình, ít nhất nó không nói chuyện.',
  'Cuộc sống giống như một bài hát, nhưng tôi bị kẹt ở phần điệp khúc tệ nhất.',
  'Tôi không mất niềm tin, tôi chỉ chưa bao giờ có nó.',
  'Tôi có một ngày tuyệt vời: không ai hỏi tôi có ổn không.',
  'Cuộc sống giống như một cái điện thoại, hết pin thì chẳng ai quan tâm.',
  'Tôi không ghét bản thân, tôi chỉ muốn bản thân biến mất một lúc.',
  'Tôi không cần bạn bè, tôi đã có bóng tối và cà phê đen.',
  'Cuộc sống giống như một trò chơi cờ vua, tôi là con tốt bị ăn đầu tiên.',
  'Tôi không buồn chán, tôi chỉ đang chờ ngày tận thế để giải trí.',
  'Tôi có một trò đùa về hy vọng, nhưng nó chết từ lâu rồi.',
  'Cuộc sống giống như một cái thang máy, chỉ toàn đi xuống.',
  'Tôi không ngủ quên, tôi chỉ đang tập chết thử vài giờ.',
  'Tôi không phải người tiêu cực, tôi chỉ thấy mặt tối của mọi thứ trước.',
  'Cuộc sống giống như một cái meme, buồn cười cho đến khi nó là về bạn.',
  'Tôi không muốn chết, tôi chỉ không muốn sống thêm chút nào.',
  'Tôi có một trái tim ấm áp, nhưng nó bị kẹt trong tủ đông.',
  'Cuộc sống giống như một cái đèn, tôi luôn tắt nó trong tâm trí.',
  'Tôi không ghét ngày thứ Hai, tôi ghét cả tuần.',
  'Tôi không thất nghiệp, tôi chỉ đang nghỉ ngơi vĩnh viễn.',
  'Cuộc sống giống như một cái ghế, tôi luôn ngồi nhầm chỗ.',
  'Tôi không sợ bóng tối, bóng tối sợ tôi cơ.',
  'Tôi có một trò đùa về ánh sáng, nhưng nó quá mờ để thấy.',
  'Cuộc sống giống như một bộ phim, tôi chỉ muốn tua đến phần kết.',
  'Tôi không lạc lối, tôi chỉ không muốn được tìm thấy.',
  'Tôi không cần tình yêu, tôi đã có sự hối hận để sưởi ấm.',
  'Cuộc sống giống như một bài kiểm tra, tôi bỏ trống mọi câu.',
  'Tôi không ghét cuộc sống, tôi chỉ thích cái chết hơn một chút.',
  'Tôi có một ngày tốt: không ai nhìn thấy tôi khóc.',
  'Cuộc sống giống như một cái đồng hồ, tôi đang chờ nó ngừng chạy.',
  'Tôi không phải người hay lo, tôi chỉ giỏi dự đoán thảm họa.',
  'Tôi không cần ánh nắng, bóng tối ôm tôi chặt hơn.',
  'Cuộc sống giống như một cái pizza, tôi chỉ muốn ném nó đi.',
  'Tôi không thất vọng, tôi chỉ mong đợi điều tồi tệ nhất.',
  'Tôi có một trò đùa về hạnh phúc, nhưng nó không vui chút nào.',
  'Cuộc sống giống như một cái giường, tôi chỉ muốn nằm mãi trên đó.',
  'Tôi không sợ chết, tôi chỉ sợ sống quá lâu.',
  'Tôi không cô đơn, tôi chỉ đang tự cách ly khỏi nhân loại.',
  'Cuộc sống giống như một cái máy giặt, tôi bị xoay đến kiệt sức.',
  'Tôi không mất hy vọng, tôi chỉ đặt nó vào nhầm chỗ.',
  'Tôi có một trò đùa về bạn bè, nhưng tôi không có ai để kể.',
  'Cuộc sống giống như một cái tủ lạnh, trống rỗng và lạnh lẽo.',
  'Tôi không buồn, tôi chỉ đang luyện tập cho ngày tận thế.',
  'Tôi không cần động lực, tôi đã quen với việc không làm gì.',
  'Cuộc sống giống như một cái bàn, tôi luôn đập đầu vào nó.',
  'Tôi không ghét mọi thứ, tôi chỉ yêu thích sự trống rỗng.',
  'Tôi có một ngày tuyệt vời: không ai hỏi tôi có kế hoạch gì.',
  'Cuộc sống giống như một cái bóng, luôn đi theo nhưng không nói gì.',
  'Tôi không tuyệt vọng, tôi chỉ đang chờ ai đó tắt đèn đời tôi.',
  'Tôi không sợ hãi, tôi chỉ thích ôm lấy nỗi buồn.',
  'Cuộc sống giống như một cái điện thoại, tôi luôn để chế độ im lặng.',
  'Tôi không cần ai cứu, tôi chỉ muốn chìm sâu hơn.',
  'Tôi có một trò đùa về ánh sáng, nhưng tôi thích bóng tối hơn.',
  'Cuộc sống giống như một cái ghế đẩu, tôi luôn ngã khỏi nó.',
  'Tôi không ghét bản thân, tôi chỉ không muốn gặp lại mình.',
  'Tôi không cần bạn bè, tôi có những suy nghĩ đen tối làm bạn.',
  'Cuộc sống giống như một cái xe, tôi luôn hết xăng giữa đường.',
  'Tôi không mất ngủ, tôi chỉ thích trò chuyện với trần nhà.',
  'Tôi có một ngày tốt: không ai hỏi tôi tại sao tôi im lặng.',
  'Cuộc sống giống như một cái đèn pin, tôi không biết cách bật.',
  'Tôi không bi quan, tôi chỉ thực tế với chút gia vị chết chóc.',
  'Tôi không cần hy vọng, tôi đã quen với bóng tối rồi.',
  'Cuộc sống giống như một cái gương, tôi chỉ thấy những vết nứt.',
  'Tôi không sợ chết, tôi chỉ sợ phải sống thêm một ngày nữa.',
  'Tôi có một trò đùa về tình yêu, nhưng nó đã tan vỡ từ lâu.',
  'Cuộc sống giống như một cái bút, tôi luôn hết mực khi cần viết.',
  'Tôi không cô độc, tôi chỉ thích ở một mình với nỗi buồn.',
  'Tôi không cần ánh sáng, tôi đã quen với việc lạc lối.',
  'Cuộc sống giống như một cái đồng hồ cát, tôi chỉ chờ nó cạn.',
  'Tôi không ghét ngày mới, tôi chỉ thích đêm cũ hơn.',
  'Tôi có một trò đùa về cuộc sống, nhưng nó quá thật để cười.',
  'Cuộc sống giống như một cái bánh, tôi chỉ muốn ai đó ăn nó giùm.',
  'Tôi không cần ai hiểu, tôi chỉ cần ai đó rời đi.',
  'Tôi không tuyệt vọng, tôi chỉ đang tận hưởng sự trống rỗng.',
  'Lập trình viên giỏi là người có thể viết code mà chính họ không hiểu sau 6 tháng.',
  'Cuộc sống của lập trình viên: 10% code, 90% Google.',
  'Tôi không debug, tôi chỉ nói chuyện với code cho đến khi nó chịu chạy.',
  'Lập trình viên không ngủ, họ chỉ tạm nghỉ để cà phê tái khởi động họ.',
  'Code của tôi chạy lần đầu, nhưng đó là trong giấc mơ.',
  'Lập trình viên không thích ánh sáng, họ yêu màu xanh của màn hình lỗi.',
  'Tôi không lười, tôi chỉ đang tối ưu hóa thời gian bằng cách không test code.',
  'Bug không phải lỗi, đó là tính năng chưa được ghi chú.',
  'Lập trình viên không có bạn gái, họ có GitHub làm người yêu.',
  'Tôi không viết code dở, tôi chỉ đang thử nghiệm mức chịu đựng của người dùng.',
  'Cuộc sống của lập trình viên giống như vòng lặp vô hạn: ăn, code, ngủ.',
  'Tôi không quên commit, tôi chỉ thích làm việc ở nhánh bí mật.',
  'Lập trình viên không thích họp, họ thích tranh cãi với compiler hơn.',
  'Code của tôi giống như hành tây, mở từng lớp chỉ khiến bạn khóc.',
  'Tôi không chậm, tôi chỉ đang chờ server trả lời câu hỏi triết học.',
  'Lập trình viên không thất bại, họ chỉ tìm ra 404 cách không hoạt động.',
  'Tôi không thích JavaScript, nhưng nó cứ bám theo tôi như ex.',
  'Bug giống như bạn thân, luôn xuất hiện khi bạn không mong đợi.',
  'Lập trình viên không nghỉ ngơi, họ chỉ tạm dừng để Ctrl+S.',
  'Tôi không viết code dài, tôi chỉ đang kể một câu chuyện sử thi.',
  'Lập trình viên không sợ deadline, họ sợ code không compile.',
  'Tôi không quên đóng dấu chấm phẩy, tôi chỉ đang thử phong cách mới.',
  'Code của tôi giống như thơ, không ai hiểu ngoài tôi.',
  'Lập trình viên không thích giao tiếp, họ thích nói chuyện bằng comment.',
  'Tôi không phải junior dev, tôi chỉ là senior trong việc debug.',
  'Cuộc sống của lập trình viên giống như JSON: không có gì là đúng thứ tự.',
  'Tôi không thích Python, nhưng nó cứ dụ tôi bằng cú pháp đơn giản.',
  'Lập trình viên không có ngày nghỉ, họ chỉ có ngày không code được.',
  'Tôi không viết bug, tôi chỉ tạo cơ hội học hỏi cho người khác.',
  'Code của tôi giống như ma trận, đẹp nhưng không ai giải được.',
  'Lập trình viên không thích sáng sớm, họ thích sáng bug đêm khuya.',
  'Tôi không quên push code, tôi chỉ đang chờ khoảnh khắc hoàn hảo.',
  'Lập trình viên không thích tài liệu, họ thích đoán mò.',
  'Tôi không làm việc nhóm, tôi chỉ làm việc với chính mình qua git clone.',
  'Code của tôi giống như câu đố, ngay cả tôi cũng không biết đáp án.',
  'Lập trình viên không thích họp mặt, họ thích họp với terminal.',
  'Tôi không viết code bừa bãi, tôi chỉ đang thử nghiệm nghệ thuật lập trình.',
  'Bug không phải vấn đề, vấn đề là khi khách hàng phát hiện ra nó.',
  'Lập trình viên không thích ánh nắng, họ thích ánh sáng từ màn hình IDE.',
  'Tôi không quên viết test, tôi chỉ tin tưởng code mình quá mức.',
  'Code của tôi giống như rượu, để lâu càng khó uống.',
  'Lập trình viên không thích giải thích, họ thích để lại comment "works fine".',
  'Tôi không thích CSS, nhưng nó cứ làm tôi mất ngủ.',
  'Lập trình viên không có sở thích, họ chỉ thích sửa lỗi người khác.',
  'Tôi không viết code lặp, tôi chỉ yêu vòng lặp for quá thôi.',
  'Code của tôi giống như phim kinh dị, đầy bất ngờ và lỗi.',
  'Lập trình viên không thích deadline, họ thích delay-line.',
  'Tôi không quên merge nhánh, tôi chỉ thích sống với xung đột.',
  'Lập trình viên không thích nói chuyện, họ thích nói qua console.log.',
  'Code của tôi giống như mê cung, tôi là người duy nhất lạc trong đó.',
  'Tôi không thích họp nhóm, tôi chỉ họp với stack overflow.',
  'Lập trình viên không thích tài liệu, họ thích reverse engineering.',
  'Tôi không viết code chậm, tôi chỉ đang tối ưu hóa hiệu suất não.',
  'Code của tôi giống như trò chơi, chạy được là thắng.',
  'Lập trình viên không thích sáng tạo, họ thích copy-paste.',
  'Tôi không thích regex, nhưng nó cứ xuất hiện như cơn ác mộng.',
  'Lập trình viên không có đời sống xã hội, họ có Discord.',
  'Code của tôi giống như thời tiết, không ai đoán trước được.',
  'Tôi không quên backup, tôi chỉ thích sống nguy hiểm.',
  'Lập trình viên không thích làm việc nhóm, họ thích làm việc với AI.',
  'Tôi không viết code dài dòng, tôi chỉ đang kể chuyện bằng cú pháp.',
  'Code của tôi giống như bánh mì, ngon nhưng đầy lỗ hổng.',
  'Lập trình viên không thích ngủ, họ thích crash cùng server.',
  'Tôi không thích Java, nhưng nó cứ mời tôi một cốc memory leak.',
  'Lập trình viên không thích giải thích bug, họ thích đổ lỗi cho user.',
  'Code của tôi giống như câu chuyện cổ tích, kết thúc bằng lỗi 500.',
  'Tôi không quên deploy, tôi chỉ thích giữ code ở local mãi mãi.',
  'Lập trình viên không thích khách hàng, họ thích yêu cầu từ chính mình.',
  'Tôi không viết code khó hiểu, tôi chỉ đang thử thách tương lai của tôi.',
  'Code của tôi giống như ma thuật, hoạt động mà không ai hiểu sao.',
  'Lập trình viên không thích deadline, họ thích làm việc khi mọi người đã ngủ.',
  'Tôi không thích họp, tôi chỉ thích debug trong im lặng.',
  'Lập trình viên không có bạn, họ có commit log làm bạn tâm giao.',
  'Code của tôi giống như trò đùa, buồn cười nhưng không ai hiểu.',
  'Tôi không quên viết tài liệu, tôi chỉ thích để lại bí ẩn.',
  'Lập trình viên không thích sáng sớm, họ thích sáng bug đêm muộn.',
  'Tôi không thích C++, nhưng nó cứ làm tôi rối như mối tình đầu.',
  'Code của tôi giống như câu hỏi triết học, tại sao nó chạy?',
  'Lập trình viên không thích nghỉ ngơi, họ thích nghỉ ngơi trong lỗi.',
  'Tôi không viết code thừa, tôi chỉ đang chuẩn bị cho tương lai.',
  'Lập trình viên không thích giao tiếp, họ thích giao tiếp qua API.',
  'Code của tôi giống như bóng tối, đẹp nhưng đầy bí ẩn.',
  'Tôi không thích họp nhóm, tôi chỉ họp với chính mình qua git diff.',
  'Lập trình viên không thích tài liệu, họ thích để lại code tự giải thích.',
  'Tôi không quên fix bug, tôi chỉ thích sống chung với nó.',
  'Code của tôi giống như một giấc mơ, đẹp cho đến khi bạn tỉnh dậy.',
  'Lập trình viên không thích sáng tạo, họ thích Ctrl+C Ctrl+V.',
  'Tôi không thích PHP, nhưng nó cứ làm tôi nhớ đến những ngày xưa cũ.',
  'Lập trình viên không thích ngủ, họ thích nhìn chằm chằm vào màn hình đen.',
  'Code của tôi giống như một cái bẫy, tôi tự rơi vào đó.',
  'Tôi không thích họp mặt, tôi chỉ thích họp với terminal.',
  'Lập trình viên không thích deadline, họ thích làm việc khi mọi người đã quên.',
  'Tôi không viết code bừa, tôi chỉ đang thử nghiệm thuyết hỗn loạn.',
  'Code của tôi giống như một bài hát, lặp đi lặp lại nhưng không ai thích.',
  'Lập trình viên không thích giải thích, họ thích để lại comment "trust me bro".',
  'Tôi không thích bug, nhưng bug cứ thích tôi.',
  'Lập trình viên không có cuộc sống, họ có cuộc sống trong IDE.'
]